### PR TITLE
Removes legacy dot syntax for dojo modules

### PR DESCRIPTION
**Pull request by westfall**
Hi Josef,

After upgrading a project to EPiServer 10, I found that your package was unfortunately incompatible.  
The issue is described in EPiServer [release note CMS-2295](http://world.episerver.com/documentation/Release-Notes/ReleaseNote/?releaseNoteId=CMS-2295). 

Please also update the package on nuget.org 😃

### CODE REVIEW

**Comment by joseftw** [comment]
Hey! Im in Atlanta for a couple of days without my computer, will fix asap when Im back home!

**Comment by westfall** [comment]
Hi again, have a good time in Atlanta 😊

**Review by joseftw — APPROVED** [review]
Will create a new package when im home.

**Comment by joseftw** [comment]
Version 1.0.0 should be available on nuget now.

**Comment by westfall** [comment]
Thank you Josef 😊

**Pull request merged**
